### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Rukaan** [RoMELDE/SkillSimulator#1]
Hi

I am a player from SEA and really love your work
But it seems i can't change the language from japanese to english
Is it currently on development ?

I switch the localstorage but it seems still not working and i try to read your code

I can't find your contact in profile, so i try to contact you here

**Comment by WindWT** [comment]
This site is no longer maintained, please use the official skill simulator. [https://ro.xd.com/moniqi/#/](url)

Besides, skill description are bounded with data, which means they cannot be easily switched.
If anyone want to fork this repo and implement translation, they should extract skill datas from their local server.
